algs = [
    #底1
    "r'",
    "r",
    "r' R' r",
    "R r R'",
    "r' R' r R'",
    "R r R' r",
    "r' R' r R",
    "R' r' R r",
    #底2
    "r R' r' R",
    "R' r R r'",
    "r R' r R r",
    "r' R' r' R r'",
    #中2
    "r R r R r'",
    "r' R' r R r R'",
    #"R' b' r b",
    "B' r' R r z",
    "r R'",
    "R' r",
    "r' R' r'",
    "R r R",
    "R' r' R r' R'",
    "r R r' R r",
    #後2
    "r R' r R'",
    "r' R",
    #"R b' r' b",
    "B r' R' r z",
    "R' r' R'",
    "r R r",
    "r R' r' R' r'",
    "R' r R r R",
    "r' R' r R' r'",
    "R r R' r R",

    #立2
    "R' r R r' R'",
    "r R' r' R r",
    "R r R' r' R'",
    "r' R' r R r",
    "r R' r'",
    "R' r R",
    "R r R r'",
    "r' R' r' R",
    "r R r' R",
    "R' r' R r'",
    "R' r R' r' R",
    "r R' r R r'",
    
    #橫2
    "R r R' r' R' r'",
    "r' R' r R r R",
    "r R r R",
    "R' r' R' r'",
    "B R B' R r'",
    #"b' r' b r' R",
    "r' R' r R' B z",
    "r R' r",
    "R' r R'",
    "R' r'",
    "r R",
    "r' R'",
    "R r",
    "R' r R r R'",
    "r R' r' R' r",
    "r R r' R r'",
    "R' r' R r' R",
    "r' B R' B'",
    #"R b' r b",
    "B r' R r z",


    #斜2
    "R' r R' r'",
    "r R' r R",
    "r R' r' R'",
    "R' r R r",
    "R r R' r' R",
    "r' R' r R r'",
    "r R r'",
    "R' r' R",
    "R' r R r' R",
    "r R' r' R r'",
    "R r R r' R'",
    "r' R' r' R r",

]

algs = [
    #底1順
    "r' B r'",
    "r R r' R' B'",
    "B' r' B r' B",
    "r' B r' B'",
    "B' r' B r'",
    "r R r' R' B",
    "B' r' B r' B'",
    #底1順1逆
    "r' B r' B",
    #底1逆
    "B r' B",
    "B' R' B R r",
    "r B r' B r'",
    "B r' B r",
    "r B r' B",
    "B' R' B R r'",
    "r B r' B r",

    #對底
    "r R r R B' R r'",
    "r' B r B'",
    "B r' B' r",
    "r' B r B' r",
    "B r' B' r B'",
    "r' B r B' r'",
    "B r' B' r B",
    "r R r R B' R",
    #"R' r' R' r' b' r'",
    "R' r' R' r' z' r' R'",

    #對1順
    "B r",
    "r R r' R' B r",
    "B R r R'",
    "B r B",
    "R' B' R' r' R'",
    "B r B'",
    "r' B r",
    #對1順1逆
    "R' B' R' r' R' B'",
    #對1逆
    "r' B'",
    "B' R' B R r' B'",
    "r' R' B' R",
    "r' B' r'",
    "R r R B R",
    "r' B' r",
    "B r' B'",

    #2上
    "B' r",
    "r B'",
    "B' r' R r' R'",
    "r B R' B R",
    "R' B' R r",
    "R r R' B'",

    "R' B' R B' r'",
    "R r R' r B",
    "r R' B' R",
    "B' R r R'",
    "r' R' B' R B'",
    "B R r R' r",
]